# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20170602_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
    ]
