# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20170602_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
