# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 13:58
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20170610_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='order',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orders',
            field=jsonfield.fields.JSONField(default='[]'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
