# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 14:17
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_auto_20170612_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='orders',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
    ]
