# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0010_auto_20170610_2031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('nxt_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcenter_nxt_node', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcenter_order', to='delivery.Order')),
                ('pcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcenter', to=settings.AUTH_USER_MODEL)),
                ('prv_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcenter_prv_node', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
