# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
