# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20170601_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='superservice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.SuperService'),
        ),
    ]
