# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_superservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedlocation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
