# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_supportedlocation_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportedlocation',
            old_name='field',
            new_name='locations',
        ),
        migrations.RemoveField(
            model_name='supportedlocation',
            name='address',
        ),
    ]
