# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20170601_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportedlocation',
            name='name',
        ),
    ]
