# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_supportedlocation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
