# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_checklist_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='name',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='description',
        ),
    ]
